init.d

diff --git a/devops_app/init/devops_app b/devops_app/init/devops_app
--- a/devops_app/init/devops_app
+++ b/devops_app/init/devops_app
@@ -1,171 +1,96 @@
 #!/bin/sh
-
-#Orginal repo: https://github.com/chovy/node-startup
-
-NODE_ENV="production"
-PORT="3000"
-APP_DIR="/opt/devops-aws/devops_app"
-NODE_APP="app.js"
-CONFIG_DIR="$APP_DIR"
-PID_DIR="$APP_DIR/pid"
-PID_FILE="$PID_DIR/app.pid"
-LOG_DIR="$APP_DIR/log"
-LOG_FILE="$LOG_DIR/app.log"
-NODE_EXEC=$(which node)
-
-###############
-
-# REDHAT chkconfig header
-
-# chkconfig: - 58 74
-# description: node-app is the script for starting a node app on boot.
 ### BEGIN INIT INFO
-# Provides: node
-# Required-Start:    $network $remote_fs $local_fs
-# Required-Stop:     $network $remote_fs $local_fs
+# Provides:
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: start and stop node
-# Description: Node process for app
+# Short-Description: Start daemon at boot time
+# Description:       Enable service provided by daemon.
 ### END INIT INFO
 
-###############
+# From https://github.com/fhd/init-script-template
 
-USAGE="Usage: $0 {start|stop|restart|status} [--force]"
-FORCE_OP=false
+dir="/opt/devops-aws/devops_app"
+user="node"
+cmd="npm start"
 
-pid_file_exists() {
-    [ -f "$PID_FILE" ]
-}
+name=`basename $0`
+pid_file="/var/run/$name.pid"
+stdout_log="/var/log/$name.log"
+stderr_log="/var/log/$name.err"
 
 get_pid() {
-    echo "$(cat "$PID_FILE")"
+    cat "$pid_file"
 }
 
 is_running() {
-    PID=$(get_pid)
-    ! [ -z "$(ps aux | awk '{print $2}' | grep "^$PID$")" ]
+    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
 }
-
-start_it() {
-    mkdir -p "$PID_DIR"
-    mkdir -p "$LOG_DIR"
-
-    echo "Starting node app ..."
-    echo PORT="$PORT" NODE_ENV="$NODE_ENV" NODE_CONFIG_DIR="$CONFIG_DIR" $NODE_EXEC "$APP_DIR/$NODE_APP"
-    PORT="$PORT" NODE_ENV="$NODE_ENV" NODE_CONFIG_DIR="$CONFIG_DIR" $NODE_EXEC "$APP_DIR/$NODE_APP"  1>"$LOG_FILE" 2>&1 &    
-    echo $! > "$PID_FILE"
-    echo "Node app started with pid $!"
-}
-
-stop_process() {
-    PID=$(get_pid)
-    echo "Killing process $PID"
-    kill $PID
-}
-
-remove_pid_file() {
-    echo "Removing pid file"
-    rm -f "$PID_FILE"
-}
-
-start_app() {
-    if pid_file_exists
-    then
-        if is_running
-        then
-            PID=$(get_pid)
-            echo "Node app already running with pid $PID"
-            exit 1
-        else
-            echo "Node app stopped, but pid file exists"
-            if [ $FORCE_OP = true ]
-            then
-                echo "Forcing start anyways"
-                remove_pid_file
-                start_it
-            fi
-        fi
-    else
-        start_it
-    fi
-}
-
-stop_app() {
-    if pid_file_exists
-    then
-        if is_running
-        then
-            echo "Stopping node app ..."
-            stop_process
-            remove_pid_file
-            echo "Node app stopped"
-        else
-            echo "Node app already stopped, but pid file exists"
-            if [ $FORCE_OP = true ]
-            then
-                echo "Forcing stop anyways ..."
-                remove_pid_file
-                echo "Node app stopped"
-            else
-                exit 1
-            fi
-        fi
-    else
-        echo "Node app already stopped, pid file does not exist"
-        exit 1
-    fi
-}
-
-status_app() {
-    if pid_file_exists
-    then
-        if is_running
-        then
-            PID=$(get_pid)
-            echo "Node app running with pid $PID"
-        else
-            echo "Node app stopped, but pid file exists"
-        fi
-    else
-        echo "Node app stopped"
-    fi
-}
-
-case "$2" in
-    --force)
-        FORCE_OP=true
-    ;;
-
-    "")
-    ;;
-
-    *)
-        echo $USAGE
-        exit 1
-    ;;
-esac
 
 case "$1" in
     start)
-        start_app
+    if is_running; then
+        echo "Already started"
+    else
+        echo "Starting $name"
+        cd "$dir"
+        sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
+        echo $! > "$pid_file"
+        if ! is_running; then
+            echo "Unable to start, see $stdout_log and $stderr_log"
+            exit 1
+        fi
+    fi
     ;;
-
     stop)
-        stop_app
-    ;;
+    if is_running; then
+        echo -n "Stopping $name.."
+        kill `get_pid`
+        for i in {1..10}
+        do
+            if ! is_running; then
+                break
+            fi
 
+            echo -n "."
+            sleep 1
+        done
+        echo
+
+        if is_running; then
+            echo "Not stopped; may still be shutting down or shutdown may have failed"
+            exit 1
+        else
+            echo "Stopped"
+            if [ -f "$pid_file" ]; then
+                rm "$pid_file"
+            fi
+        fi
+    else
+        echo "Not running"
+    fi
+    ;;
     restart)
-        stop_app
-        start_app
-    ;;
-
-    status)
-        status_app
-    ;;
-
-    *)
-        echo $USAGE
+    $0 stop
+    if is_running; then
+        echo "Unable to stop, will not attempt to start"
         exit 1
+    fi
+    $0 start
+    ;;
+    status)
+    if is_running; then
+        echo "Running"
+    else
+        echo "Stopped"
+        exit 1
+    fi
+    ;;
+    *)
+    echo "Usage: $0 {start|stop|restart|status}"
+    exit 1
     ;;
 esac
+
+exit 0
